# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    default_locale: '%locale%'
    #default_locale: 'ru'
    
    trusted_proxies: ['nginx']

    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

    # Note that the session will be started ONLY if you read or write from it.
    #session: true
    session:
        handler_id: 'redis://redis'
        enabled: true

        cookie_secure: auto
        cookie_samesite: lax

        #cookie_lifetime: 84600
        #gc_maxlifetime:  84600

    #error_controller: App\Controller\ErrorController::show
    error_controller: '%env(ERROR_CONTROLLER)%'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
