monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                #level: debug
                level: error
                max_files: 30        # Хранить 30 файлов логов
                file_permission: 0664
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: debug  # Логировать начиная с debug-уровня
                handler: nested
                excluded_http_codes: []  # Убрали исключение для 405
                buffer_size: 50
            not_found:
                type: stream
                path: "%kernel.logs_dir%/not_found.log"
                level: warning
                channels: ["request"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/prod.log"  # Пишем в файл вместо stderr
                level: debug
                formatter: monolog.formatter.line  # Более читаемый формат
            errors:
                type: stream
                path: "%kernel.logs_dir%/error.log"
                level: error
                channels: ["!event"]

when@old_prod2:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: debug
                handler: nested
                excluded_http_codes: [404,405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
