framework:
    default_locale: 'ru'
    translator:
        #default_path: '%kernel.project_dir%/translations'
        #default_path: '%kernel.project_dir%/translations/global'
        paths:
            - '%kernel.project_dir%/translations/screenshots'
        providers:
        fallbacks: ['ru']
