# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.name:   '%env(APP_NAME)%'
    app.author: '%env(APP_AUTHOR)%'
    app.supported_locales: ['ru', 'en']
    kernel.default_locale: 'ru'
    locale: 'ru'
    #env(APP_MAINTENANCE): 'off'
    #env(APP_MAINTENANCE_ALLOWED_IPS): ''
    #app.maintenance.enabled: '%env(bool:APP_MAINTENANCE)%'
    #app.maintenance_flag: 'off'
    

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventSubscriber\MaintenanceSubscriber:
        arguments:
            $twig: '@twig'
            $profiler: '@?profiler'
            $allowedIps: '%env(json:APP_MAINTENANCE_ALLOWED_IPS)%'
            $maintenanceFlag: '%env(APP_MAINTENANCE)%'
        autowire: false

    App\Service\ScreenshotService:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $httpClient: '@GuzzleHttp\Client'
            $filesystem: '@Symfony\Component\Filesystem\Filesystem'
            
    GuzzleHttp\Client:
        arguments:
            - base_uri: 'http://browserless:3000/'
              timeout: 60
              headers:
                User-Agent: 'My Symfony App'
